
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/res/res.js",
	"libs/modules/eui/eui.js",
	"libs/modules/tween/tween.js",
	"libs/modules/game/game.js",
	"libs/modules/socket/socket.js",
	"promise/promise.js",
	"libs/bundle/bundle.js",
	"bin-debug/app/ui/base/BasePanel.js",
	"bin-debug/app/gambling/core/BaseServerInfo.js",
	"bin-debug/app/ui/base/BaseAnmiatePanel.js",
	"bin-debug/libs/collections/Dictionary.js",
	"bin-debug/app/ui/renderer/BaseItemRenderer.js",
	"bin-debug/libs/net/BaseSocket.js",
	"bin-debug/app/global/handler/ReLoginingHandler.js",
	"bin-debug/app/scenes/BaseScene.js",
	"bin-debug/app/ui/base/BackHomeAnimePanel.js",
	"bin-debug/app/activity/handler/SignInHandler.js",
	"bin-debug/app/animation/BaseAnimation.js",
	"bin-debug/app/achievement/AchieveProcessManager.js",
	"bin-debug/app/ui/component/BaseComponent.js",
	"bin-debug/app/ui/panel/gamblingpanel/BaseGamblingPanelSupport.js",
	"bin-debug/app/global/handler/InitAppHandler.js",
	"bin-debug/app/global/handler/InitServerHandler.js",
	"bin-debug/core/channel/handler/ChannelBase.js",
	"bin-debug/core/version/UpdateHandler.js",
	"bin-debug/defined/BaseDefined.js",
	"bin-debug/enums/GameEnums.js",
	"bin-debug/libs/call/CallDispatcher.js",
	"bin-debug/libs/call/Delegate.js",
	"bin-debug/libs/call/DelegateDispatcher.js",
	"bin-debug/app/friend/BaseFriendInfo.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/BaseGamblingHeadState.js",
	"bin-debug/app/ui/panel/EnterRoomPwdPanel.js",
	"bin-debug/app/ui/panel/GameScenePanel.js",
	"bin-debug/Main.js",
	"bin-debug/app/animation/AnimationEnum.js",
	"bin-debug/app/animation/AnimationFactory.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/app/animation/CardFaceBoardAppear.js",
	"bin-debug/app/animation/CardFaceBright.js",
	"bin-debug/app/animation/CardFaceMoveToPoint.js",
	"bin-debug/app/animation/CardFaceTurnToFace.js",
	"bin-debug/app/animation/CommonMoveToPointByNowPos.js",
	"bin-debug/app/animation/CommonMoveToRelativelyPos.js",
	"bin-debug/app/animation/FlopCardAnimation.js",
	"bin-debug/app/animation/GamblingGameGroupMove.js",
	"bin-debug/app/animation/IAnimationHandler.js",
	"bin-debug/app/animation/SelfCard1Appear.js",
	"bin-debug/app/animation/SelfCard2Appear.js",
	"bin-debug/app/animation/WinChipsAnim.js",
	"bin-debug/app/assets/LoadConfig.js",
	"bin-debug/app/award/AwardExchangeErrorType.js",
	"bin-debug/app/award/AwardManager.js",
	"bin-debug/app/award/AwardTimesInfo.js",
	"bin-debug/app/championship/ChampionshipAwardInfo.js",
	"bin-debug/app/championship/ChampionshipManager.js",
	"bin-debug/app/championship/ChampionshipRankInfo.js",
	"bin-debug/app/championship/EntranceTicketType.js",
	"bin-debug/app/championship/JoinChampionshipWay.js",
	"bin-debug/app/championship/MatchOutsInfo.js",
	"bin-debug/app/championship/MatchRoomInfo.js",
	"bin-debug/app/championship/MTTJoinNumInfo.js",
	"bin-debug/app/championship/OutsInfo.js",
	"bin-debug/app/chat/ChatManager.js",
	"bin-debug/app/chat/RecordAudioManager.js",
	"bin-debug/app/achievement/AchievementManager.js",
	"bin-debug/app/friend/FriendInfo.js",
	"bin-debug/app/friend/FriendManager.js",
	"bin-debug/app/friend/FriendUIType.js",
	"bin-debug/app/gambling/GamblingCardTypeMatch.js",
	"bin-debug/app/gambling/GamblingManager.js",
	"bin-debug/app/gambling/GamblingProcess.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/app/gambling/core/IGamblingHandler.js",
	"bin-debug/app/gambling/data/PlayerInfo.js",
	"bin-debug/app/gambling/data/RoomInfo.js",
	"bin-debug/app/gambling/handler/HandCardHandler.js",
	"bin-debug/app/global/GameManager.js",
	"bin-debug/app/global/GoCardProcessManager.js",
	"bin-debug/app/achievement/process/FlushProcess.js",
	"bin-debug/app/achievement/process/FourOfAKindProcess.js",
	"bin-debug/app/achievement/process/FriendProcess.js",
	"bin-debug/app/localstorage/PrefsManager.js",
	"bin-debug/app/login/LoginInfo.js",
	"bin-debug/app/login/LoginManager.js",
	"bin-debug/app/login/ServerInfo.js",
	"bin-debug/app/mail/MailInfo.js",
	"bin-debug/app/mail/MailManager.js",
	"bin-debug/app/pay/CostManager.js",
	"bin-debug/app/pay/ShoppingManager.js",
	"bin-debug/app/playingField/PlayingFieldManager.js",
	"bin-debug/app/playingField/PlayingFieldRoomInfo.js",
	"bin-debug/app/prize/PrizeEffectType.js",
	"bin-debug/app/prize/PrizeInfo.js",
	"bin-debug/app/prize/PrizeManager.js",
	"bin-debug/app/prize/PrizeState.js",
	"bin-debug/app/property/ItemManager.js",
	"bin-debug/app/property/PropertyManager.js",
	"bin-debug/app/property/data/ItemGetInfo.js",
	"bin-debug/app/property/data/ItemInfo.js",
	"bin-debug/app/rank/RankChange.js",
	"bin-debug/app/rank/RankInfo.js",
	"bin-debug/app/rank/RankManager.js",
	"bin-debug/app/rank/RankName.js",
	"bin-debug/app/safeBox/SafeBoxManager.js",
	"bin-debug/app/safeBox/SafeBoxPanel.js",
	"bin-debug/app/achievement/process/FullhouseProcess.js",
	"bin-debug/app/scenes/GameScene.js",
	"bin-debug/app/scenes/HallScene.js",
	"bin-debug/app/scenes/LoginScene.js",
	"bin-debug/app/scenes/SceneManager.js",
	"bin-debug/app/sound/SoundManager.js",
	"bin-debug/app/ui/AlertManager.js",
	"bin-debug/app/ui/UIManager.js",
	"bin-debug/app/achievement/process/GoldProcess.js",
	"bin-debug/app/achievement/process/HighPatternProcess.js",
	"bin-debug/app/achievement/process/LevelProcess.js",
	"bin-debug/app/ui/component/ActionEffectComponent.js",
	"bin-debug/app/achievement/process/LevelUpProcess.js",
	"bin-debug/app/ui/component/CardFaceComponent.js",
	"bin-debug/app/ui/component/ChipsShowComponent.js",
	"bin-debug/app/ui/component/CommonIcon.js",
	"bin-debug/app/ui/component/GamblingActionComponent.js",
	"bin-debug/app/ui/component/GamblingCdComponent.js",
	"bin-debug/app/ui/component/GamblingHeadComponent.js",
	"bin-debug/app/ui/component/GameButton.js",
	"bin-debug/app/ui/component/GameButtonGroup.js",
	"bin-debug/app/ui/component/NumComponent.js",
	"bin-debug/app/ui/component/TabComponent.js",
	"bin-debug/app/ui/component/UserInfoComponent.js",
	"bin-debug/app/ui/component/WinCardComponent.js",
	"bin-debug/app/achievement/process/MiddlePatternProcess.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadActionedState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadCardAnimationSupport.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadEmptyState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadFoldState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadOnActionState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadRoundStartState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadSitDownState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadThanTheCardState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadWaitActionState.js",
	"bin-debug/app/ui/component/gamblingHeadComponent/GamblingHeadWiatNextState.js",
	"bin-debug/app/ui/events/UIModuleEvent.js",
	"bin-debug/app/ui/panel/AAModelPanel.js",
	"bin-debug/app/ui/panel/AchievementItemPanel.js",
	"bin-debug/app/ui/panel/AddChipsPanel.js",
	"bin-debug/app/ui/panel/AlertInfoPanel.js",
	"bin-debug/app/ui/panel/AssignmentPanel.js",
	"bin-debug/app/ui/panel/AudioRecordingPanel.js",
	"bin-debug/app/ui/panel/BuyAccessGamePanel.js",
	"bin-debug/app/ui/panel/ChampionshipInfoPanel.js",
	"bin-debug/app/ui/panel/ChampionshipPanel.js",
	"bin-debug/app/ui/panel/ChangeUserNamePanel.js",
	"bin-debug/app/ui/panel/ChatPanel.js",
	"bin-debug/app/ui/panel/CreateRolePanel.js",
	"bin-debug/app/ui/panel/CreateRoomPwdPanel.js",
	"bin-debug/app/ui/panel/EditUserInfoPanel.js",
	"bin-debug/app/ui/panel/EnterLoginPanel.js",
	"bin-debug/app/achievement/process/OnePairProcess.js",
	"bin-debug/app/ui/panel/FriendMsgPanel.js",
	"bin-debug/app/ui/panel/FriendPanel.js",
	"bin-debug/app/ui/panel/GamblingPanel.js",
	"bin-debug/app/ui/panel/GameHallPanel.js",
	"bin-debug/app/ui/panel/GameRulePanel.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/app/ui/panel/GetCoinTipsPanel.js",
	"bin-debug/app/ui/panel/InviteFriendPanel.js",
	"bin-debug/app/ui/panel/InviteMsgPanel.js",
	"bin-debug/app/ui/panel/JoinChampionshipSuccessPanel.js",
	"bin-debug/app/ui/panel/KeyBoardPanel.js",
	"bin-debug/app/ui/panel/LoadingPanel.js",
	"bin-debug/app/ui/panel/LoadingSwitchPanel.js",
	"bin-debug/app/ui/panel/LoginBar.js",
	"bin-debug/app/ui/panel/LoginLocalPanel.js",
	"bin-debug/app/ui/panel/LoginPanel.js",
	"bin-debug/app/ui/panel/LoginSceneBgPanel.js",
	"bin-debug/app/ui/panel/MailPanel.js",
	"bin-debug/app/ui/panel/MarqueePanel.js",
	"bin-debug/app/ui/panel/MinuteRemindPanel.js",
	"bin-debug/app/ui/panel/NetworkPanel.js",
	"bin-debug/app/ui/panel/PlayingFieldPanel.js",
	"bin-debug/app/ui/panel/PrizePanel.js",
	"bin-debug/app/ui/panel/RankPanel.js",
	"bin-debug/app/ui/panel/RegisterPanel.js",
	"bin-debug/app/ui/panel/SecondRemindPanel.js",
	"bin-debug/app/ui/panel/SetPanel.js",
	"bin-debug/app/ui/panel/ShareGamePanel.js",
	"bin-debug/app/ui/panel/ShoppingPanel.js",
	"bin-debug/app/ui/panel/SignInPanel.js",
	"bin-debug/app/ui/panel/TestPanel.js",
	"bin-debug/app/ui/panel/TextInfoPanel.js",
	"bin-debug/app/ui/panel/TextTipsPanel.js",
	"bin-debug/app/ui/panel/UserAngreementPanel.js",
	"bin-debug/app/ui/panel/UserInfoPanel.js",
	"bin-debug/app/ui/panel/VipPanel.js",
	"bin-debug/app/ui/panel/activitypanel/ActivityPanel.js",
	"bin-debug/app/ui/panel/activitypanel/NormalActivityPanel.js",
	"bin-debug/app/ui/panel/activitypanel/SimplePicturePanel.js",
	"bin-debug/app/ui/panel/gamblingpanel/AudioRecordButton.js",
	"bin-debug/app/achievement/process/PrimaryPatternProcess.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelActionSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelButtonPosSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelFlopCardSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelInfoRefreshSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelMoveSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelOneLoopOverSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelPitDataSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelPitTurnSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelRoundOverSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelSetting.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPanelSitDownAndAddCoinSupport.js",
	"bin-debug/app/ui/panel/gamblingpanel/GamblingPitInfo.js",
	"bin-debug/app/ui/panel/gamblingpanel/GameEffectLogic.js",
	"bin-debug/app/ui/panel/gamblingpanel/TimeShowLogic.js",
	"bin-debug/app/ui/panel/gamehallpanel/PiaohuaAnime.js",
	"bin-debug/app/ui/renderer/AchievementItemRenderer.js",
	"bin-debug/app/ui/renderer/ActivityAwardItemRenderer.js",
	"bin-debug/app/ui/renderer/ActivityItemRenderer.js",
	"bin-debug/app/ui/renderer/AddFriendItemRenderer.js",
	"bin-debug/app/ui/renderer/AssignmentItemRenderer.js",
	"bin-debug/app/ui/renderer/AwardItemRenderer.js",
	"bin-debug/app/achievement/process/RoyalFlushProcess.js",
	"bin-debug/app/ui/renderer/BlindItemRenderer.js",
	"bin-debug/app/ui/renderer/ChampionshipItemRenderer.js",
	"bin-debug/app/ui/renderer/ChampionshipRankItemRenderer.js",
	"bin-debug/app/ui/renderer/ChatItemRenderer.js",
	"bin-debug/app/ui/renderer/ChipsShowRenderer.js",
	"bin-debug/app/ui/renderer/CreateRoomPanelItemRenderer.js",
	"bin-debug/app/ui/renderer/DiamondListItemRenderer.js",
	"bin-debug/app/ui/renderer/FaceItemRenderer.js",
	"bin-debug/app/ui/renderer/FastChatItemRenderer.js",
	"bin-debug/app/ui/renderer/FriendItemRenderer.js",
	"bin-debug/app/ui/renderer/FriendRequestItemRenderer.js",
	"bin-debug/app/ui/renderer/GiftItemRenderer.js",
	"bin-debug/app/ui/renderer/GoldListItemRenderer.js",
	"bin-debug/app/ui/renderer/InviteFriendListItemRenderer.js",
	"bin-debug/app/ui/renderer/MailItemRenderer.js",
	"bin-debug/app/ui/renderer/MyAwardPanelItemRenderer.js",
	"bin-debug/app/ui/renderer/MyTicketItemRenderer.js",
	"bin-debug/app/ui/renderer/OutsChildItemRenderer.js",
	"bin-debug/app/ui/renderer/OutsItemRenderer.js",
	"bin-debug/app/ui/renderer/PersonalRoomItemRenderer.js",
	"bin-debug/app/ui/renderer/PlayingFieldItemRenderer.js",
	"bin-debug/app/ui/renderer/RankItemRenderer.js",
	"bin-debug/app/ui/renderer/SignInGoldItemRenderer.js",
	"bin-debug/app/ui/renderer/TextRenderer.js",
	"bin-debug/app/ui/renderer/VipListItemRenderer.js",
	"bin-debug/app/user/RoundInfo.js",
	"bin-debug/app/user/UserInfo.js",
	"bin-debug/app/user/UserManager.js",
	"bin-debug/app/user/UserUtil.js",
	"bin-debug/app/utils/ColorUtil.js",
	"bin-debug/app/utils/DragUtil.js",
	"bin-debug/app/utils/SortUtil.js",
	"bin-debug/app/utils/UIUtil.js",
	"bin-debug/app/vip/VipManager.js",
	"bin-debug/app/vip/VipType.js",
	"bin-debug/core/channel/ChannelManager.js",
	"bin-debug/core/channel/ChannelUtil.js",
	"bin-debug/core/channel/ExtFuncName.js",
	"bin-debug/core/channel/handler/Channel_android.js",
	"bin-debug/core/channel/handler/Channel_ios.js",
	"bin-debug/core/channel/handler/Channel_web.js",
	"bin-debug/app/achievement/process/StraightFlushProcess.js",
	"bin-debug/core/http/UpLoader.js",
	"bin-debug/core/http/URLLoader.js",
	"bin-debug/core/net/NetUtil.js",
	"bin-debug/core/net/SocketManager.js",
	"bin-debug/core/time/SystemTimeManager.js",
	"bin-debug/core/time/TimeManager.js",
	"bin-debug/app/achievement/process/StraightProcess.js",
	"bin-debug/core/version/VersionManager.js",
	"bin-debug/core/version/VersionUtil.js",
	"bin-debug/defined/AchieveDefined.js",
	"bin-debug/defined/ActivityListDefined.js",
	"bin-debug/defined/AwardDefined.js",
	"bin-debug/app/achievement/process/ThreeOfAKindProcess.js",
	"bin-debug/defined/CardDefined.js",
	"bin-debug/defined/ChampionshipBlindDefined.js",
	"bin-debug/defined/ChampionshipDefined.js",
	"bin-debug/defined/ChampionshipPrizeDefined.js",
	"bin-debug/defined/ChipDefined.js",
	"bin-debug/defined/DefinedManager.js",
	"bin-debug/defined/ErrorDefined.js",
	"bin-debug/defined/ExpDefined.js",
	"bin-debug/defined/FastChatDefined.js",
	"bin-debug/defined/ForbiddenDefined.js",
	"bin-debug/defined/ItemDefined.js",
	"bin-debug/defined/MailDefined.js",
	"bin-debug/defined/MusicDefined.js",
	"bin-debug/defined/NameDefined.js",
	"bin-debug/defined/PayDefined.js",
	"bin-debug/defined/ProjectDefined.js",
	"bin-debug/defined/RoomDefined.js",
	"bin-debug/defined/ShortNameDefined.js",
	"bin-debug/defined/SignInDefined.js",
	"bin-debug/defined/SystemTimeDefined.js",
	"bin-debug/defined/TextDefined.js",
	"bin-debug/enums/Command.js",
	"bin-debug/app/achievement/process/TwoPairsProcess.js",
	"bin-debug/enums/GameSetting.js",
	"bin-debug/app/achievement/process/WinProcess.js",
	"bin-debug/app/activity/ActivityInfo.js",
	"bin-debug/app/activity/ActivityManager.js",
	"bin-debug/app/activity/ActivityOpenState.js",
	"bin-debug/app/activity/ActivityType.js",
	"bin-debug/libs/net/GameSocket.js",
	"bin-debug/libs/net/LoginSocket.js",
	"bin-debug/libs/net/SocketInfo.js",
	"bin-debug/libs/net/SocketMessage.js",
	"bin-debug/libs/net/SpRpcResult.js",
	"bin-debug/libs/utils/ArrayUtil.js",
	"bin-debug/libs/utils/Crypt.js",
	"bin-debug/libs/utils/DateTimeUtil.js",
	"bin-debug/libs/utils/FilterUtil.js",
	"bin-debug/libs/utils/FuncUtil.js",
	"bin-debug/libs/utils/MathUtil.js",
	"bin-debug/libs/utils/PoolUtil.js",
	"bin-debug/libs/utils/StringUtil.js",
	"bin-debug/libs/utils/TextUtil.js",
	"bin-debug/libs/utils/Tick.js",
	"bin-debug/libs/utils/Vecotr2D.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 50,
		scaleMode: "showAll",
		contentWidth: 1280,
		contentHeight: 720,
		showPaintRect: true,
		showFPS: true,
		fpsStyles: "x:0,y:0,size:12,textColor:0xffffff,bgAlpha:0.2",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};